---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-yaml
          - id: check-xml
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: detect-private-key
          - id: check-added-large-files
            args: ['--maxkb=950']
          - id: check-json
            exclude: (.vscode|.devcontainer)
          - id: detect-aws-credentials
            args: [--allow-missing-credentials]
          - id: pretty-format-json
            args: [--autofix]

    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.20.0
      hooks:
          - id: commitizen
            stages: [commit-msg]

    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v6.0.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ['@commitlint/config-conventional']

    - repo: https://github.com/gitguardian/gg-shield
      rev: v1.10.5
      hooks:
          - id: ggshield
            language_version: python3
            stages: [commit]

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.4.1
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@2.1.2
            stages: [commit]
