---

- hosts: all
  become: true
  become_method: sudo

  vars:
    users_group_add_list:
      - name: deployer

    users_add_list:
      - name: ansible
        unlimited_superuser: true
        ssh_key:  "<ssh_public_key>"

  roles:
    - role: ansible-users  