version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - config/db.env
    volumes:
      - semaphore-mysql-dbdata:/var/lib/mysql
    networks:
      - ansible-ui

  semaphore:
    image: ansiblesemaphore/semaphore:latest
    container_name: semaphore
    expose:
      - 3000
    env_file:
      - config/semaphore.env
    environment:
      SEMAPHORE_PLAYBOOK_PATH: "/tmp/semaphore/"
    depends_on:
      - db
    networks:
      - ansible-ui

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    expose:
      - 8080
    networks:
      - ansible-ui

  reverse-proxy:
    image: caddy:2.3.0
    container_name: reverse-proxy
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./config:/etc/caddy
    restart: unless-stopped
    networks:
      - ansible-ui

  start_dependencies:
    image: dadarek/wait-for-dependencies
    command: db:3306 semaphore:3000 adminer:8080 reverse-proxy:3000
    depends_on:
      - db
      - adminer
      - semaphore
      - reverse-proxy
    environment:
      SLEEP_LENGTH: 1
      TIMEOUT_LENGTH: 60
    networks:
      - ansible-ui

volumes:
  semaphore-mysql-dbdata:

networks:
  ansible-ui:
    driver: bridge