---
- import_playbook: git-checkout.yml

- name: Configure control-center
  hosts: control-center

  vars:
      USER_HOME: '/home/ubuntu'

  pre_tasks:
      - name: Upgrade Ansible && Install Ansible Role Dependencies
        ansible.builtin.shell: provision/common/install_to_cc.sh
        args:
            chdir: ansible-control-center/

      - name: Create a directory if it does not exist
        ansible.builtin.file:
            path: '{{ item }}'
            state: directory
            mode: '0440'
        with_items:
            - '{{ USER_HOME }}/ansible-managed/certs'

  tasks:
      - name: Copy  SSL certificates to Host
        tags: ssl_certs
        ansible.builtin.copy:
            src: '../keys/{{ item }}'
            dest: '{{ USER_HOME }}/ansible-managed/certs/{{ item }}'
            owner: root
            group: root
            mode: 'u=rw,g=r,o=' # mode: '0440'
        with_items:
            - ssl_certificate.crt
            - ssl_certificate_key.key

      - name: Copy SSH Config to Host
        tags: ssh_keys
        ansible.builtin.copy:
            src: 'config/ssh-config'
            dest: '{{ USER_HOME }}/.ssh/config'
            mode: 'u=rw,g=r,o=r'

      - name: Copy SSH Private Key
        tags: ssh_private_key
        ansible.builtin.copy:
            src: '../keys/id_rsa'
            dest: '{{ USER_HOME }}/.ssh/id_rsa'
            mode: 'u=rw,g=,o='

      - name: Copy Ansible Vault File
        tags: vault_password
        ansible.builtin.copy:
            src: '../keys/.vault_password'
            dest: '{{ USER_HOME }}/ansible-managed/.vault_password'
            mode: 'u=rw,g=r,o=r'

  post_tasks:
      - name: Add Ansible inventory mappings to /etc/hosts
        blockinfile:
            path: /etc/hosts
            block: |
                {% for host in groups['all'] %}
                {{ hostvars[host].ansible_ssh_host }} {{ host }}
                {% endfor %}
        become: true
        become_method: sudo
