---

- hosts: control-center

  tasks:
    - name: Add Ansible inventory mappings to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {% for host in groups['all'] %}
          {{ hostvars[host].ansible_ssh_host }} {{ host }}
          {% endfor %}
      become: true
      become_method: sudo

    - name: Copy  SSH Config to Host
      tags: ssl_certs
      ansible.builtin.copy:
        src: "config/ssh-config"
        dest: "/home/ubuntu/.ssh/config"
        mode: "u=rw,g=r,o=r"

    - name: Copy  Private Key to Host
      tags: ssh_private_key
      ansible.builtin.copy:
        src: "../keys/id_rsa"
        dest: "/home/ubuntu/.ssh/id_rsa"
        mode: "u=rw,g=,o="




