---

- name: Linux Reboot 
  hosts: control-center
  gather_facts: no
  become: true
  become_method: sudo
 
  tasks:
    - name: Reboot the machine (Wait for 5 min)
      reboot:
        reboot_timeout: 300